import test from 'node:test';
import assert from 'node:assert/strict';
import { CALCULATOR_ID, createReportService, createRepository, reportPath } from '../src/report-history.mjs';

const payload = () => ({ preparedFor: 'Client', inputs: { address: '123 Test St', purchasePrice: 200000 }, results: { profit: 50000 }, reportDate: 'September 23, 2026' });
function fixture(options = {}) {
  const rows = new Map(), files = new Map(), states = [];
  let renders = 0, uploads = 0, sequence = 0;
  const original = new Blob(['%PDF-original'], { type: 'application/pdf' });
  const repository = {
    async insert(row) { if (!rows.has(row.id)) rows.set(row.id, structuredClone(row)); return structuredClone(rows.get(row.id)); },
    async existing(row) { return files.get(reportPath(row)) || null; },
    async upload(row, pdf) { uploads++; files.set(reportPath(row), pdf); },
    async ready(row) { const ready = { ...row, pdf_status: 'ready' }; rows.set(row.id, ready); return ready; },
    async download(row) { return files.get(reportPath(row)); },
    ...options.repository,
  };
  const service = createReportService({ repository, render: options.render || (async () => { renders++; return original; }),
    onState: (_, state) => states.push(state), uuid: () => `report-${++sequence}` });
  service.setOwner('user-a');
  return { service, repository, rows, files, states, original, get renders() { return renders; }, get uploads() { return uploads; } };
}

test('guests create no history, and analysis snapshots cannot be changed by later edits', async () => {
  const f = fixture();
  f.service.setOwner(null);
  assert.equal(f.service.capture(payload()), null);
  f.service.setOwner('user-a');
  const input = payload(), job = f.service.capture(input);
  input.inputs.purchasePrice = 1;
  await f.service.start(job);
  assert.equal(f.rows.get(job.row.id).payload.inputs.purchasePrice, 200000);
  assert.equal(job.row.calculator_id, CALCULATOR_ID);
  assert.notEqual(job.row.calculator_id, '75c69418-565e-43bf-bc7d-b09d9f591e1f');
  assert.equal(job.row.title, 'Client — 123 Test St');
  assert.deepEqual(f.states, ['saving', 'saved']);
});

test('parallel downloads and later retries reuse the exact uploaded PDF and one report', async () => {
  const f = fixture(), job = f.service.capture(payload());
  const [a, b] = await Promise.all([f.service.start(job), f.service.start(job)]);
  assert.equal(a, b);
  const c = await f.service.start(job);
  assert.equal(await c.text(), '%PDF-original');
  assert.equal(f.renders, 1);
  assert.equal(f.uploads, 1);
  assert.equal(f.rows.size, 1);
});

test('an upload followed by interrupted finalization is recovered without rendering again', async () => {
  const f = fixture(), job = f.service.capture(payload());
  const ready = f.repository.ready;
  f.repository.ready = async () => { throw new Error('connection lost'); };
  await assert.rejects(f.service.start(job));
  f.repository.ready = ready;
  await f.service.resume(f.rows.get(job.row.id));
  assert.equal(f.renders, 1);
  assert.equal(f.uploads, 1);
  assert.equal(job.row.pdf_status, 'ready');
});

test('upload response loss recovers the original bytes already stored', async () => {
  const f = fixture(), upload = f.repository.upload;
  f.repository.upload = async (...args) => { await upload(...args); throw new Error('response lost'); };
  const pdf = await f.service.start(f.service.capture(payload()));
  assert.equal(await pdf.text(), '%PDF-original');
  assert.equal(f.renders, 1);
});

test('failed upload retains the original generated bytes for retry', async () => {
  const f = fixture(), upload = f.repository.upload, job = f.service.capture(payload());
  f.repository.upload = async () => { throw new Error('offline'); };
  await assert.rejects(f.service.start(job));
  f.repository.upload = upload;
  await f.service.start(job);
  assert.equal(f.renders, 1);
});

test('switching accounts during rendering cannot upload or finalize the old account report', async () => {
  let release, began;
  const started = new Promise((r) => { began = r; });
  const f = fixture({ render: () => { began(); return new Promise((r) => { release = r; }); } });
  const job = f.service.capture(payload()), work = f.service.start(job);
  await started;
  f.service.setOwner('user-b');
  release(new Blob(['%PDF-original']));
  await assert.rejects(work, /account changed/);
  assert.equal(f.uploads, 0);
  assert.equal(f.rows.get(job.row.id).pdf_status, 'pending');
  await assert.rejects(f.service.start(job), /account changed/);
});

test('ready PDFs are not regenerated if their original is missing', async () => {
  const f = fixture(), job = f.service.capture(payload());
  await f.service.start(job);
  f.files.clear();
  await assert.rejects(f.service.start(job), /original PDF is unavailable/);
  assert.equal(f.renders, 1);
});

test('other calculator payloads can be downloaded but cannot be rendered here', async () => {
  const f = fixture();
  const other = { id: 'other-report', calculator_id: 'other-calculator', user_id: 'user-a', payload_schema_version: 7, pdf_status: 'ready', payload: { entirely: 'different' } };
  f.files.set(reportPath(other), f.original);
  assert.equal(await (await f.service.download(other)).text(), '%PDF-original');
  await assert.rejects(f.service.resume(other), /original calculator version/);
  await assert.rejects(f.service.download({ ...other, user_id: 'user-b' }), /Sign in/);
});

test('repository filters history by owner, optionally calculator, and paginates without loading payloads', async () => {
  const calls = [];
  const query = Object.fromEntries(['select', 'eq', 'order'].map((name) => [name, (...args) => { calls.push([name, ...args]); return query; }]));
  query.range = async (...args) => { calls.push(['range', ...args]); return { data: Array.from({ length: 21 }, (_, id) => ({ id })) }; };
  const repository = createRepository({ from: () => query, storage: { from: () => ({}) } });
  const page = await repository.list({ userId: 'user-a', calculatorId: 'other', offset: 20 });
  assert.equal(page.rows.length, 20);
  assert.equal(page.hasMore, true);
  assert.ok(calls.some((c) => JSON.stringify(c) === JSON.stringify(['eq', 'user_id', 'user-a'])));
  assert.ok(calls.some((c) => JSON.stringify(c) === JSON.stringify(['eq', 'calculator_id', 'other'])));
  assert.deepEqual(calls.at(-1), ['range', 20, 40]);
  assert.ok(!calls[0][1].split(',').includes('payload'));
});
